name: mingw

on: 
  push:

jobs:
  build_test:
    runs-on: windows-latest
    name: 'Mingw build'
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          cmake -S . -B build -G 'MinGW Makefiles'
          cmake --build build
      